---
abstract: 'Mock package, object and standard subroutines, with unit testing in mind.'
author:
  - 'Steve Bertrand <steveb@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.3, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mock-Sub
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Scalar::Util: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/stevieb9/mock-sub/issues
  repository: https://github.com/stevieb9/mock-sub.git
version: '1.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
